let stateName={
    "florida":'FL',
    'newjersey':'NJ',
    'california':'CA',
    'texas':'TX',
    'newyork':'NY',
    'connecticut':'CT',
    'ohio':"OH",
    'georgia':'GA',
    'northcarolina':'NC',
    'southcarolina':'SC',
    'missouri':'MO',
    'alabama':'AL',
    'arizona':'AZ',
    'alaska':'AK',
    'arkansas':'AK',
    'colorado':'CO',
    'delaware':'DE',
    'districtofcolumbia':'DC',
    'hawaii':'HI',
    'idaho':'ID',
    'illinois':'IL',
    'indiana':'IN',
    'iowa':'IA',
    'kansas':'KS',
    'kentucky':'KY',
    'louisiana':'LA',
    'maine':'ME',
    'maryland':'MD',
    'massachusetts':'MA',
    'michigan':'MI',
    'minnesota':'MN',
    'mississippi':'MS',
    'montana':'MT',
    'nebraska':'NE',
    'nevada':'NV',
    'newhampshire':'NH',
    'newmexico':'NM',
    'northdakota':'ND',
    'oklahoma':'OK',
    'oregon':'OR',
    'pennsylvania':'PA',
    'rhodeisland':'RI',
    'southdakota':'SD',
    'tennessee':'TN',
    'utah':'UT',
    'vermont':'VT',
    'virginia':'VA',
    'washington':'WA',
    'westvirginia':'WV',
    'wisconsin':'WI',
    'wyoming':'WY'
}

let USstates=[
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'connecticut',
    'Colorado',
    'Delaware',
    'District of Columbia',
    "Florida",
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Missouri',
    'Mississippi',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Mexico',
    'New Jersey',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'Westvirginia',
    'Wisconsin',
    'Wyoming'
]

export {stateName,USstates}